<a href="https://colab.research.google.com/github/tajeshwar74/scikit-learn/blob/main/One_Hot_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
d = {'sales': [100000,222000,1000000,522000,111111,222222,1111111,20000,75000,90000,1000000,10000],
'city': ['Tampa','Tampa','Orlando','Jacksonville','Miami','Jacksonville','Miami','Miami','Orlando','Orlando','Orlando','Orlando'],
'size': ['Small', 'Medium','Large','Large','Small','Medium','Large','Small','Medium','Medium','Medium','Small',]}

In [3]:
df = pd.DataFrame(data=d)

In [6]:
df.head()

     sales          city    size
0   100000         Tampa   Small
1   222000         Tampa  Medium
2  1000000       Orlando   Large
3   522000  Jacksonville   Large
4   111111         Miami   Small

In [8]:
df['city'].unique()

array(['Tampa', 'Orlando', 'Jacksonville', 'Miami'], dtype=object)

In [9]:
from sklearn.preprocessing import OneHotEncoder

In [14]:
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False).set_output(transform='pandas')

In [19]:
ohetransform = ohe.fit_transform(df[['city']])

In [21]:
ohetransform.head()

   city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0                0.0         0.0           0.0         1.0
1                0.0         0.0           0.0         1.0
2                0.0         0.0           1.0         0.0
3                1.0         0.0           0.0         0.0
4                0.0         1.0           0.0         0.0

In [22]:
df = pd.concat([df, ohetransform], axis=1).drop(columns=['city'])

In [23]:
df.head()

     sales    size  city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0   100000   Small                0.0         0.0           0.0         1.0
1   222000  Medium                0.0         0.0           0.0         1.0
2  1000000   Large                0.0         0.0           1.0         0.0
3   522000   Large                1.0         0.0           0.0         0.0
4   111111   Small                0.0         1.0           0.0         0.0