<a href="https://colab.research.google.com/github/tajeshwar74/scikit-learn/blob/main/SimpleImputer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame({'miles': [20, 48, np.nan, 28, 43, 48]})

In [ ]:
df

   miles
0   20.0
1   48.0
2    NaN
3   28.0
4   43.0
5   48.0

In [2]:
from sklearn.impute import SimpleImputer

In [ ]:
imp_mean = SimpleImputer(strategy='mean')

In [ ]:
imp_mean.fit_transform(df)

array([[20. ],
       [48. ],
       [37.4],
       [28. ],
       [43. ],
       [48. ]])

In [ ]:
imp_median = SimpleImputer(strategy='median')

In [ ]:
imp_median.fit_transform(df)

array([[20.],
       [48.],
       [43.],
       [28.],
       [43.],
       [48.]])

In [ ]:
imp_mode = SimpleImputer(strategy='most_frequent')

In [ ]:
imp_mode.fit_transform(df)

array([[20.],
       [48.],
       [48.],
       [28.],
       [43.],
       [48.]])

In [9]:
imp_constant = SimpleImputer(strategy='constant', fill_value=13)

In [ ]:
imp_constant.fit_transform(df)

array([[20.],
       [48.],
       [13.],
       [28.],
       [43.],
       [48.]])

In [ ]:
#categorical data
names = pd.DataFrame({'name': ['billy', 'tommy', 'jackson', np.nan, 'chloe']})

In [ ]:
names

      name
0    billy
1    tommy
2  jackson
3      NaN
4    chloe

In [8]:
imp_constant_cat = SimpleImputer(strategy='constant', fill_value='gekko')

In [ ]:
imp_constant_cat.fit_transform(names)

array([['billy'],
       ['tommy'],
       ['jackson'],
       ['gekko'],
       ['chloe']], dtype=object)

In [ ]:
imp_mean_marked = SimpleImputer(strategy='mean', add_indicator=True)

In [ ]:
imp_mean_marked.fit_transform(df)

array([[20. ,  0. ],
       [48. ,  0. ],
       [37.4,  1. ],
       [28. ,  0. ],
       [43. ,  0. ],
       [48. ,  0. ]])

In [5]:
df = pd.DataFrame({'name': ['Ryan', 'Nolan', 'Walter', np.nan, 'Napolean'],
                   'miles': [50,62,np.nan,100,26]})

In [6]:
df

       name  miles
0      Ryan   50.0
1     Nolan   62.0
2    Walter    NaN
3       NaN  100.0
4  Napolean   26.0

In [3]:
#
from sklearn.compose import make_column_transformer

In [11]:
ct = make_column_transformer(
    (imp_constant_cat, ['name']),
    (imp_constant, ['miles']),
    remainder='drop'
)

In [12]:
ct.set_output(transform='pandas')

ColumnTransformer(transformers=[('simpleimputer-1',
                                 SimpleImputer(fill_value='gekko',
                                               strategy='constant'),
                                 ['name']),
                                ('simpleimputer-2',
                                 SimpleImputer(fill_value=13,
                                               strategy='constant'),
                                 ['miles'])])

In [13]:
df_ct = ct.fit_transform(df)

In [14]:
df_ct

  simpleimputer-1__name  simpleimputer-2__miles
0                  Ryan                    50.0
1                 Nolan                    62.0
2                Walter                    13.0
3                 gekko                   100.0
4              Napolean                    26.0